User story #168: Showing custom errors in newproject.sh
Throwing error messages to stderr and also to a log file

Change-Id: Ib7631dc08f9bc365d384037da1e2aa3f6defc555

diff --git a/puppet/modules/runtime_project/templates/gerrit/newproject.sh.erb b/puppet/modules/runtime_project/templates/gerrit/newproject.sh.erb
--- a/puppet/modules/runtime_project/templates/gerrit/newproject.sh.erb
+++ b/puppet/modules/runtime_project/templates/gerrit/newproject.sh.erb
@@ -1,6 +1,14 @@
 #!/bin/bash
 # Copyright 2013 Hewlett-Packard Development Company, L.P
 
+die(){
+  local msg=$1
+  local logfile=$2
+  [ -n "$msg" ] && echo $msg 1>&2
+  [ -n "$logfile" ] && echo $msg >> $logfile
+  exit 1
+}
+
 _NEW_PROJECT_NAME=$1
 _NEW_GROUP_NAME=$_NEW_PROJECT_NAME #$2
 _NEW_PROJECT_DESCRIPTION="description for $_NEW_PROJECT_NAME project" #$3
@@ -15,51 +23,46 @@ _SSH_CMD="<%= scope.lookupvar("::runtime_project::params::ssh_cmd") %> -oStrictH
 _WORKSPACE="<%= scope.lookupvar("::runtime_project::params::git_home") %>/workspace/$$"
 _LOG_FOLDER="<%= scope.lookupvar("::runtime_project::params::git_home") %>/workspace/log"
 _LOG_FILE="${_LOG_FOLDER}/$(date '+%Y-%m-%d-%H%M%S').log"
+_PROJECT_CONFIG="$_WORKSPACE/$_GIT_PROJECT/modules/runtime_project/files/gerrit/acls/production/$_NEW_PROJECT_NAME.config"
+_PROJECTS_YAML="$_WORKSPACE/$_GIT_PROJECT/modules/runtime_project/templates/gerrit/config/production/review.projects.yaml.erb"
 _COMMIT_MSG="Adding $_NEW_PROJECT_NAME project to gerrit from the UI"
 
-exec 1>$_LOG_FILE 2>&1
 
 mkdir -p $_WORKSPACE
 mkdir -p $_LOG_FOLDER
 cd $_WORKSPACE
-echo 'Creating Project ...'
+echo "Creating Project: $_NEW_PROJECT_NAME" >> $_LOG_FILE
 export GIT_SSH=$_GIT_SSH_CONFIG
 _RESPONSE=$($_SSH_CMD -T > /dev/null 2<&1; echo $?)
+
 if !(test $_RESPONSE -eq 127) then
-  echo 'forj-config repo is not available.'
-  exit 1
+  die 'forj-config repo is not available.' $_LOG_FILE
 fi
 
 if [[ $_NEW_PROJECT_NAME == *' '* ]]
 then
-  echo "Project name can't have spaces."
-  exit 1
+  die "Project name can't have spaces." $_LOG_FILE
 fi
 
-if ($_SSH_CMD gerrit ls-projects | grep -x $_NEW_PROJECT_NAME) then
-  echo 'The project already exists, choose another name.'
-  exit 1
+if ($_SSH_CMD gerrit ls-projects | grep -x $_NEW_PROJECT_NAME > /dev/null 2<&1;) then
+  die 'The project already exists, choose another name.' $_LOG_FILE
 fi
 
-if ($_SSH_CMD gerrit query project:$_GIT_PROJECT status:open message:$_NEW_PROJECT_NAME | grep "$_COMMIT_MSG") then
-  echo 'Duplicated request.'
-  exit 1
+if ($_SSH_CMD gerrit query project:$_GIT_PROJECT status:open message:$_NEW_PROJECT_NAME | grep "$_COMMIT_MSG" > /dev/null 2<&1;) then
+  die 'Duplicated request.' $_LOG_FILE
 fi
 
 git clone ssh://$_GIT_USER@$_REVIEW_SERVER:29418/$_GIT_PROJECT
+
+if [ ! -f "${_PROJECTS_YAML}" ] ; then
+  die "${_GIT_PROJECT} not ready... missing ${_PROJECTS_YAML}." $_LOG_FILE
+fi
+
 
 if [[ $_NEW_PROJECT_NAME == */* ]]
 then
   var=$(echo $_NEW_PROJECT_NAME | awk -F"/" '{print $1}')
   mkdir "$_WORKSPACE/$_GIT_PROJECT/modules/runtime_project/files/gerrit/acls/production/$var"
-fi
-
-_PROJECT_CONFIG="$_WORKSPACE/$_GIT_PROJECT/modules/runtime_project/files/gerrit/acls/production/$_NEW_PROJECT_NAME.config"
-_PROJECTS_YAML="$_WORKSPACE/$_GIT_PROJECT/modules/runtime_project/templates/gerrit/config/production/review.projects.yaml.erb"
-
-if [ ! -f "${_PROJECTS_YAML}" ] ; then
-  echo "${_GIT_PROJECT} not ready... missing ${_PROJECTS_YAML}, skipping"
-  exit 1
 fi
 
 echo 'creating files...'
@@ -93,6 +96,6 @@ git config --unset-all user.name
 git config --unset-all user.email
 
 #Cleaning workspace
-echo 'removing workspace process'
+echo 'Removing workspace process' >> $_LOG_FILE
 rm -r $_WORKSPACE
 exit 0
